version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: bemyrider-db
    environment:
      POSTGRES_DB: bemyrider
      POSTGRES_USER: bemyrider
      POSTGRES_PASSWORD: bemyrider123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bemyrider"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Applicazione Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bemyrider-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://bemyrider:bemyrider123@db:5432/bemyrider
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_data:
